name: 'playstore_analytics'
version: '1.0.0'
profile: 'your_project_name'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  playstore_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts