version: 2

models:
  - name: stg_playstore_apps
    description: "Cleaned staging model for Play Store apps"
    columns:
      - name: app_id
        tests:
          - not_null
          - unique
      - name: title
        tests:
          - not_null

  - name: stg_playstore_reviews
    description: "Cleaned staging model for Play Store reviews"
    columns:
      - name: review_id
        tests:
          - not_null
          - unique
      - name: app_id
        tests:
          - not_null